### ISSUE TITLE
error during comiling the code

### ISSUE THREAD

**Issue by sanehdeep2012** [reger-men/Arduion-POV-clock#1]
dear reger-men

thanks for your hear work and shere with us,

but when compiling the code i get the following code

H:\EAGLE\EAGLE_PROJECT_ARDUINO\TEMP PROJECTS\POV\Arduion-POV-clock-master\Arduion-POV-clock-master\clock\clock.ino:3:20: fatal error: Time.h: No such file or directory

   #include <Time.h>

```
                ^
```

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.
http://downloads.arduino.cc/packages/package_index.json file signature verification failed. File ignored.

**Comment by reger-men** [comment]
Hello,

include "Time.h" should solve this problem, Please make sure , that both files (Time.h and clock.ino) into the same Folder.

best regards
reger-men

Date: Mon, 18 Apr 2016 03:40:16 -0700

**Comment by sanehdeep2012** [comment]
dear reger-men

thanks for your reply and feed back

but i have not find any Time.h file in my folder and also not found at your site and github kindly share the same with me , also i have not found in arduino setup folder,

kindly share the Time.h file with is releated to this project

**Comment by reger-men** [comment]
The Time library adds timekeeping functionality to Arduino with or without external timekeeping hardware.
Here is Link to Time

https://github.com/johnmccombs/arduino-libraries/tree/master/Time
Date: Mon, 18 Apr 2016 22:25:30 -0700

**Comment by sanehdeep2012** [comment]
thanks dear reger-men,

thaks you very much i got the file and compile the code again and now no error is comming, 
just one thing is left how to use the sensor, to compleate the project,

can you share the schematic of project,

**Comment by reger-men** [comment]
sorry I don't have it any more.

Date: Tue, 19 Apr 2016 05:11:35 -0700

**Comment by sanehdeep2012** [comment]
any way thanks for your support, my project is working mow i will workout
on sensor pin

thanks reger-man
